#pragma once
// Canonical version. Update via tools/version-bump.ps1.
#define FOLDERPAD_VERSION_MAJOR 1
#define FOLDERPAD_VERSION_MINOR 1
#define FOLDERPAD_VERSION_PATCH 0
#define FP_STRINGIFY_INNER(x) #x
#define FP_STRINGIFY(x) FP_STRINGIFY_INNER(x)
#define FP_WIDEN_INNER(x) L##x
#define FP_WIDEN(x) FP_WIDEN_INNER(x)
#define FOLDERPAD_VERSION_STRING FP_STRINGIFY(FOLDERPAD_VERSION_MAJOR) "." FP_STRINGIFY(FOLDERPAD_VERSION_MINOR) "." FP_STRINGIFY(FOLDERPAD_VERSION_PATCH)
#define FOLDERPAD_VERSION_WSTRING FP_WIDEN(FP_STRINGIFY(FOLDERPAD_VERSION_MAJOR)) L"." FP_WIDEN(FP_STRINGIFY(FOLDERPAD_VERSION_MINOR)) L"." FP_WIDEN(FP_STRINGIFY(FOLDERPAD_VERSION_PATCH))
